require("plugins.colorscheme")
require("plugins.whichkey")
require("plugins.conform")
require("plugins.minipairs")
-- require("plugins.snacks")
require("plugins.trouble")
require("plugins.vimilluminate")
require("plugins.mason")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.blink")
require("plugins.gitsigns")
require("plugins.mini-statusline")
require("plugins.vim-sleuth")
