Later(function()
  Add({
    source = "MeanderingProgrammer/render-markdown.nvim",
    depends = {
      "nvim-treesitter/nvim-treesitter",
      "nvim-mini/mini.icons",
    },
  })
  require("render-markdown").setup({
    code = {
      enabled = true,
      render_modes = false,
      sign = true,
      conceal_delimiters = false,
      language = true,
      position = 'left',
      language_icon = true,
      language_name = true,
      language_info = false,
      language_pad = 0,
      disable = {},
      disable_background = { 'diff' },
      background_inset = 1,
      width = 'full',
      left_margin = 0,
      left_pad = 0,
      right_pad = 0,
      min_width = 0,
      border = 'thin',
      language_border = '█',
      language_left = '',
      language_right = '',
      above = '▄',
      below = '▀',
      inline = true,
      inline_left = '`',
      inline_right = '`',
      inline_pad = 0,
      priority = 140,
      highlight = 'RenderMarkdownCode',
      highlight_info = 'RenderMarkdownCodeInfo',
      highlight_language = nil,
      highlight_border = 'RenderMarkdownCodeBorder',
      highlight_fallback = 'RenderMarkdownCodeFallback',
      highlight_inline = 'RenderMarkdownCodeInline',
      highlight_inline_left = nil,
      highlight_inline_right = nil,
      style = 'full',
    },
    heading = {
      border = true,
      border_virtual = true,
      render_modes = { "i", "v", "x", "V" },
    },
    checkbox = {
      bullet = true,
      right_pad = 1,
      left_pad = 1,
    },
    indent = {
      enabled = false,
      render_modes = { "i", "v", "x", "V" },
    }
  })
end)
