#!/usr/bin/env bash

function _load_conf() {
  for conf in "$1"/confs/*.conf.sh; do
    [ -e "${conf}" ] && PROFILE_WORKING_PATH="$1" source "${conf}"
  done
  return 0
}

function _add_path () {
  test -d "$1" || return
  echo "$PATH" | tr ':' $'\n' | grep -e "^$1$" >/dev/null 2>&1 || export PATH="$PATH:$1"
}

PROFILE_PATH="${HOME}/.profile.d"
PLATFORM="$(uname)"

_add_path "$HOME/bin"

_load_conf "${PROFILE_PATH}/base"
_load_conf "${PROFILE_PATH}/${PLATFORM}"
