#!/usr/bin/env bash

export PATH

# Helper function for adding to PATH
function _add_path() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        PATH="$1${PATH:+":$PATH"}"
    fi
}

# Clean all duplicates from path
function _clean_path() {
  local clean_path
  clean_path="$(echo $PATH | tr : $'\n' | awk '!x[$0]++' | tr $'\n' : | sed -E 's/^:*([^:].+[^:]):*$/\1/')"
  PATH="$clean_path"
}

PROFILE_ROOT="$HOME/.profile.d"
PROFILE_STAGING="$PROFILE_ROOT/staging"
PROFILE_SCRIPTS="$PROFILE_ROOT/scripts"

for sourced_file in "$PROFILE_STAGING/source/"*; do
  PROFILE_SCRIPTS="$PROFILE_SCRIPTS" source "${sourced_file}"
done

_add_path "$HOME/bin"
_clean_path
