#!/usr/bin/env bash

__rssh_basedir="$HOME/.ssh/environments"

function __rssh_init () {
  if [ ! -d "$__rssh_basedir" ]; then
    mkdir -p "$__rssh_basedir"
    chmod 700 "$__rssh_basedir"
  fi
}

function __rssh_envfile_for_env () {
  local envname="$1"
  echo "$__rssh_basedir/$envname/agent.env"
}

function __rssh_list_envs () {
  for f in $(echo $__rssh_basedir/*); do
    echo "$(basename $f)"
  done
}

function __rssh_list () {
  for envname in $(__rssh_list_envs); do
    local envfile="$(__rssh_envfile_for_env "$envname")"
    if [ -e "$envfile" ]; then
      (
      echo "$envname"
      source "$envfile" > /dev/null
      ssh-add -l | sed 's/^/  /'
      echo "" 
      )
    fi
  done
}

function __rssh_agent_is_running () {
  ssh-add -l >/dev/null 2>&1
  if [ "$?" -eq "2" ]; then
    return 1
  fi

  return 0
}

function __rssh_initialize_env () {
  local envname="$1"
  local envfile="$(__rssh_envfile_for_env $envname)"

  if [ ! -d "$(dirname $envfile)" ]; then
    mkdir -p "$(dirname $envfile)"
  fi

  ssh-agent > "$envfile"
  source "$envfile"

  for key in "$(dirname $envfile)"/*.pub; do
    local keyfile="$(dirname $key)/$(basename $key .pub)"
    if [ -e "$keyfile" ]; then
      echo "add key: $keyfile"
      ssh-add "$keyfile"
    fi
  done
}

function __rssh_set_env () {
  local envname="$1"

  echo "The current ssh environment is: ${RSSH_ENV:-none}"
  if [ -z "$envname" ]; then
    for envname in $(__rssh_list_envs); do
      echo "  rssh set $envname"
    done
    return 1
  fi

  local envfile="$(__rssh_envfile_for_env "$envname")"

  echo "Switching from ${RSSH_ENV:-none} to $envname"
  export RSSH_ENV="$envname"
  if [ ! -e "$envfile" ]; then
    echo "No such environment: $envname / $envfile"
    echo -n "Would you like to create one? (y/n): "
    read ANSWER
    if [ "$ANSWER" != "y" ]; then
      return 0
    else
      __rssh_initialize_env "$envname"
      return 0
    fi
  fi

  source "$envfile"
  if ! __rssh_agent_is_running; then
    echo "$envname is not running, starting it"
    __rssh_initialize_env "$envname"
    return 0
  fi
}

function rssh () {
  local cmd="$1"
  __rssh_init

  if [ -z "$cmd" ]; then
    cmd="help"
  fi

  case "$1" in 
    set)
      shift
      __rssh_set_env "$@"
      ;;
    ls)
      shift
      __rssh_list "$@"
      ;;
    *)
      echo "rssh (set|ls|help)"
      echo ""
      echo "Manage multiple ssh-agent environments."
      echo ""
      echo "  set <envname>      Set the current shell environment"
      echo "  ls                 List your ssh enviornments"
      echo ""
      ;;
  esac
}
